petcare/petcare/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic.base import TemplateView
from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vets/', include ('vets.urls', namespace='vets')),
    url(r'^$',views.home,name='home'),
    #url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),


]

petcare/vets/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<lat>\d*[.]?\d+)/(?P<lon>\d*[.]?\d+)',views.locate_around_me,name='locate'), 
    url(r'^$',views.index,name='index'),
    url(r'^find/',views.search_by_place,name='search'),
    url(r'^details/(?P<p_id>.+)/',views.details,name='details'),
]

petcare/vets/models.py
# Create your models here.

#from geoposition.fields import GeopositionField
from django.db import models

class VetSpot(models.Model):

	name = models.CharField(max_length=100)
	latitude = models.FloatField()
	longitude = models.FloatField()
	address = models.TextField()
#	phone = models.TextField()
	opennow = models.BooleanField(default=False)


	class Meta:
		verbose_name_plural = 'vet spots'

petcare/petcare/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def home(request):
	return render_to_response('index.html', context_instance=RequestContext(request))

petcare/vets/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse
import googlemaps
from vets.models import VetSpot

gmaps = googlemaps.Client(key='AIzaSyA0tl-yTrvyi_9UESPKQ27Ny4L0ONoktj8')


def index(request):
	return render_to_response('search_page.html', context_instance=RequestContext(request))


def search_by_place(request):

	keyw= ""
	loc = ""

	if request.method == 'POST':
		loc = request.POST.get('location', '')
		keyw = request.POST.get('what', '')

	if not loc:
		return render_to_response('missing_location.html', context_instance=RequestContext(request))

	geocode_result = gmaps.geocode(loc)
	if not geocode_result:
		return render_to_response('incorrect_location.html', context_instance=RequestContext(request))

	lat = float(geocode_result[0]['geometry']['location']['lat'])
	lon = float(geocode_result[0]['geometry']['location']['lng'])	

	if keyw :
		search_result = gmaps.places( keyw, location=(lat,lon), types='veterinary_care', radius = 10000)
	else:
		search_result = gmaps.places( 'animal', location=(lat,lon), types='veterinary_care', radius = 10000)
	out = display_map_with_result(request, search_result, loc)
	return HttpResponse(out)


def locate_around_me(request, lat, lon):
	
	lat = float(lat)
	lon = float(lon)
	search_result = gmaps.places('animal', location=(lat,lon), types='veterinary_care', radius = 10000)
	reverse_geocode_result = gmaps.reverse_geocode((lat, lon))
	loc = reverse_geocode_result[0]['formatted_address']
	out = display_map_with_result(request, search_result, loc)
	return HttpResponse(out)


def display_map_with_result(request, search_result, place):
	vslist = []
	for r in search_result['results']:

		vs = VetSpot()
		vs.name = str(r['name'])
		vs.address = r['formatted_address']
		vs.latitude = r['geometry']['location']['lat']
		vs.longitude = r['geometry']['location']['lng']
		vs.place_id = r['place_id']

		if 'rating' in r.keys():
			vs.rating = r['rating']

		if 'opening_hours' in r.keys():
			if str(r['opening_hours']['open_now']).lower == "true":
				vs.opennow = True

		vslist.append(vs)

	return render(request, 'poi_list.html', {'pois': vslist, 'place': place})

def details(request, p_id):
	detail_result = gmaps.place(p_id)
	info = detail_result['result']	
	lat = info['geometry']['location']['lat']
	lon = info['geometry']['location']['lng']
	display_info = {}
	display_info['Name'] = info['name']
	display_info['Address'] = info['formatted_address']
	if 'formatted_phone_number' in info.keys():
		display_info['Phone'] = info['formatted_phone_number']
	if 'international_phone_number' in info.keys():
		display_info['International'] = info['international_phone_number']
	if 'opening_hours' in info.keys():
		display_info['Hours'] = info['opening_hours']		
	if 'permanently_closed' in info.keys():
		display_info['permanently_closed'] = info['permanently_closed']	
	if 'photos' in info.keys():
		display_info['photos'] = info['photos']	
	if 'price_level' in info.keys():
		display_info['expense'] = info['price_level']	
	if 'rating' in info.keys():
		display_info['rating'] = info['rating']	
	if 'reviews' in info.keys():
		display_info['reviews'] = info['reviews']
	if 'website' in info.keys():
		display_info['website'] = info['website']
	if 'vicinity' in info.keys():
		display_info['vicinity'] = info['vicinity']
	if 'url' in info.keys():
		display_info['url'] = info['url']
		
	return render(request, 'place_details.html', {'details': display_info, 'lat': lat, 'lon': lon, 'pid': p_id})

petcare/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} {% endblock %}</title>
    {% block styling %} {% endblock %}

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/grayscale.css" rel="stylesheet">

    <link href="/static/css/style.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="{% url 'home' %}">
                    <i class="fa fa-play-circle"></i>  <!-- <span class="light">Start</span> --> PetCare
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    {% block menu %} {% endblock %}
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

{% block content %} {% endblock %}
    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact PetCare</h2>
                <p>Feel free to email us to provide some feedback on our work, give us suggestions for new features, or to just say hello!</p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://github.com/Famguy/PetCare" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; PetCare 2016</p>
        </div>
    </footer>


    {% block script %}
    {% endblock %} 

    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="/static/js/jquery.easing.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/static/js/grayscale.js"></script>
    

</body>

</html>

petcare/templates/incorrect_location.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Vet Search {% endblock %}
{% block content %}  
    <!-- Search Section -->
    <section id="search" class="container content-section text-center">
    <div class="row">                       
        <p class="col-sm-12">Oops! No results returned. Please search for a valid location....</p>
        <span>
            <a href="{% url 'vets:index' %}" class="btn btn-success btn-lg">Take me back to search!</a>
        </span> 
    </div>                                                             
    </section>
{% endblock %}    

petcare/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} PetCare {% endblock %}
{% block menu %} 
    <li>
        <a class="page-scroll" href="#about">About</a>
    </li>
    <li>
        <a class="page-scroll" href="#download">Try Out</a>
    </li>
{% endblock %}
                    
{% block content %}
    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">PetCare</h1>
                        <p class="intro-text">An online portal to find pet related services.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About PetCare</h2>
                <p>We aim to provide you with services for your pets. Currently, we help you locate vets based on an address</p>
                <p>You can either search by entering a location or use your own location</p>
                <p>Also, you can view details and directions to a place</p>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Try Us Out</h2>
                    <a href="{% url 'vets:index' %}" class="btn btn-default btn-lg">Visit Search Page</a>
                </div>
            </div>
        </div>
    </section>


{% endblock %} 

petcare/templates/missing_location.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Vet Search {% endblock %}
{% block content %}  
    <!-- Search Section -->
    <section id="search" class="container content-section text-center">
    <div class="row">                       
        <p class="col-sm-12">Oops! Looks like you forgot to mention a location to search....</p>
        <span>
            <a href="{% url 'vets:index' %}" class="btn btn-success btn-lg">Take me back to search!</a>
        </span> 
    </div>                                                             
    </section>
{% endblock %}    

petcare/templates/place_details.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Details {% endblock %}
{% block menu %} 
    <li>
        <a class="page-scroll" href="#directions">Directions</a>
    </li>
    <li>
        <a class="page-scroll" href="#details">Details</a>
    </li>
{% endblock %}
{% block styling %} 
{% endblock %}
{% block content %} 
    <section id="directions"  class="container content-section-aliter text-center">
    <p>You can also view directions to the place here!</p>              
    </section>
    <input id="origin-input" class="controls" type="text"
        placeholder="Enter an origin location">

    <div id="mode-selector" class="controls">
      <input type="radio" name="type" id="changemode-walking" checked="checked">
      <label for="changemode-walking">Walking</label>

      <input type="radio" name="type" id="changemode-transit">
      <label for="changemode-transit">Transit</label>

      <input type="radio" name="type" id="changemode-driving">
      <label for="changemode-driving">Driving</label>
    </div>

    <div id="map-canvas"></div>
    <section id="details"  class="container content-section-aliter">

        <h4>{{details.Name}}</h4>
        <p class = "item"><span class="colorer">Address : </span>{{details.Address}}</p>
        {% if details.International or details.Phone %}
        <p class = "item"><span class="colorer">Phone : </span>{{details.Phone}}
          {% if details.International %}
          , {{details.International}}
          {% endif %}
        </p>
        {% endif %}
        
        {% if details.rating %}
        <p class = "item"><span class="colorer">Rating : </span>{{details.rating}}</p>
        {% endif %}
        {% if permanently_closed %}
        <p class = "item"><span class="colorer">Permanemtly Closed : </span>{{details.permanently_closed}}</p>
        {% endif %}
        {% if details.price_level %}
        <p class = "item"><span class="colorer">Price Level : </span>{{details.price_level}}</p>
        {% endif %}
        {% if details.website %}
        <p class = "item"><span class="colorer">Website </span><br><a href = "{{details.website}}" target ="_blank">{{details.website}}</a></p>
        {% endif %}
        {% if details.url %}
        <p class = "item"><span class="colorer">Official Google Page </span><br><a href = "{{details.url}}" target ="_blank">{{details.url}}</a></p>
        {% endif %}
        <!--{% if details.Hours %}
        <p class = "item"><span class="colorer">Hours : </span>{{details.Hours}}</p>
        {% endif %}
        {% if details.reviews %}
        <p class = "item"><span class="colorer">Reviews : </span>{{details.reviews}}</p>
        {% endif %}  -->                 

    </section>
{% endblock %}
{% block script %} 
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
   
        <script>
            var url = window.location.href;
            parts = url.split('/');
            loc = parts.pop();
            var urlpid = parts.pop();

            function initMap() {
              var origin_place_id = null;
              var destination_place_id = "{{ pid }}";
              var travel_mode = google.maps.TravelMode.WALKING;
              var map = new google.maps.Map(document.getElementById('map-canvas'), {
                mapTypeControl: false,
                center: {lat: {{ lat }}, lng: {{ lon }} },
                zoom: 16
              });
              var directionsService = new google.maps.DirectionsService;
              var directionsDisplay = new google.maps.DirectionsRenderer;
              directionsDisplay.setMap(map);

              var origin_input = document.getElementById('origin-input');
              var modes = document.getElementById('mode-selector');

              map.controls[google.maps.ControlPosition.TOP_LEFT].push(origin_input);
              map.controls[google.maps.ControlPosition.TOP_LEFT].push(modes);

              var origin_autocomplete = new google.maps.places.Autocomplete(origin_input);
              origin_autocomplete.bindTo('bounds', map);

                var bounds = new google.maps.LatLngBounds();
                function addMarker(lat, lng, title, info) {
                        console.log("here");
                        var position = new google.maps.LatLng(lat, lng);
                        var contentString = '<div id="content" class="map-window">'+                                         
                                            '<h3 id="firstHeading" class="firstHeading">'+title+'</h3>'+
                                            '<div id="bodyContent">'+
                                            '<p>'+info+'</p>'+
                                            '</div>'+
                                            '</div>';
                        var infowindow = new google.maps.InfoWindow({
                            content: contentString
                        });                   
                        var marker = new google.maps.Marker({
                            position: position,
                            map: map,
                            title: title
                        });
                        marker.addListener('click', function() {
                            infowindow.open(map, marker);
                        });
                        bounds.extend(position);
                    }
              addMarker({{ lat }}, {{ lon }}, "{{ details.Name }}","{{ details.Address }}");

              function setupClickListener(id, mode) {
                var radioButton = document.getElementById(id);
                radioButton.addEventListener('click', function() {
                  travel_mode = mode;
                });
              }
              setupClickListener('changemode-walking', google.maps.TravelMode.WALKING);
              setupClickListener('changemode-transit', google.maps.TravelMode.TRANSIT);
              setupClickListener('changemode-driving', google.maps.TravelMode.DRIVING);

              function expandViewportToFitPlace(map, place) {
                if (place.geometry.viewport) {
                  map.fitBounds(place.geometry.viewport);
                } else {
                  map.setCenter(place.geometry.location);
                  map.setZoom(17);
                }
              }

              origin_autocomplete.addListener('place_changed', function() {
                var place = origin_autocomplete.getPlace();
                if (!place.geometry) {
                  window.alert("Autocomplete's returned place contains no geometry for origin");
                  return;
                }
                expandViewportToFitPlace(map, place);

                origin_place_id = place.place_id;
                route(origin_place_id, destination_place_id, travel_mode,
                      directionsService, directionsDisplay);
              });

              function route(origin_place_id, destination_place_id, travel_mode,
                             directionsService, directionsDisplay) {
                if (!origin_place_id || !destination_place_id) {
                  return;
                }
                directionsService.route({
                  origin: {'placeId': origin_place_id},
                  destination: {'placeId': destination_place_id},
                  travelMode: travel_mode
                }, function(response, status) {
                  if (status === google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);
                  } else {
                    window.alert('Directions request failed due to ' + status);
                  }
                });
              }
            }

                google.maps.event.addDomListener(window, 'load', initMap);

        </script>
{% endblock %}

petcare/templates/poi_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Points of Interest {% endblock %}

{% block styling %} 
<link href="/static/css/style.css" rel="stylesheet">
{% endblock %}

{% block menu %} 
    <li>
        <a class="page-scroll" href="#mapped">Map</a>
    </li>
    <li>
        <a class="page-scroll" href="#results">View Results</a>
    </li>
{% endblock %}

{% block content %}  
    <!-- Map Section -->
    <section id="mapped"  class="container content-section-aliter text-center">                   
        <p> Showing results for {{place}}</p>  
        <span>
            <a href="{% url 'vets:index' %}" class="btn btn-default btn-lg">I want to search for some other place . . . .</a>
        </span>        
    </section>
    <div id="map-canvas"></div>
    <!-- Results Section -->
    
    <section id="results"  class="container content-section-aliter">
        {% for poi in pois %}
            <div class="entry row">
                <div>
                    <h4 class="place-title text-center">{{ poi.name }}</h4>
                </div>           
                <address>
                <p class="margin-adjuster text-left"><strong class="colorer">Address :  </strong> {{ poi.address }}</p>
                </address>
                {% if poi.rating %}
                    <p class="margin-adjuster text-left"><strong class="colorer">Rating :  </strong> {{ poi.rating }}/5</p>
                {% endif %}

                <p class="text-right margin-adjuster "><a href="{% url 'vets:details' p_id=poi.place_id %}"><small>know more</small></a></p>
            </div>

        {% endfor %}             
    </section>
      
{% endblock %}         

{% block script %} 

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA0tl-yTrvyi_9UESPKQ27Ny4L0ONoktj8"></script>
    <script>
                function initialize() {
                    var map = new google.maps.Map(document.getElementById('map-canvas'));
                    var bounds = new google.maps.LatLngBounds();

                    function addMarker(lat, lng, title, info) {
                        var position = new google.maps.LatLng(lat, lng);
                        var contentString = '<div id="content" class="map-window">'+                                         
                                            '<h3 id="firstHeading" class="firstHeading">'+title+'</h3>'+
                                            '<div id="bodyContent">'+
                                            '<p>'+info+'</p>'+
                                            '</div>'+
                                            '</div>';
                        var infowindow = new google.maps.InfoWindow({
                            content: contentString
                        });                   
                        var marker = new google.maps.Marker({
                            position: position,
                            map: map,
                            title: title
                        });
                        marker.addListener('click', function() {
                            map.setZoom(map.getZoom() + 1);
                            map.setCenter(marker.getPosition());
                        });
                        marker.addListener('mouseover', function() {
                            infowindow.open(map, marker);
                        });
                        marker.addListener('mouseout', function() {
                            infowindow.close();
                        });
                        bounds.extend(position);
                    }

                    {% for poi in pois %}
                        addMarker({{ poi.latitude }}, {{ poi.longitude }}, "{{ poi.name }}","{{ poi.address }}");
                    {% endfor %}

                    map.fitBounds(bounds);
                }

                google.maps.event.addDomListener(window, 'load', initialize);
            </script>

{% endblock %}            

petcare/templates/search_page.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Vet Search {% endblock %}
{% block styling %} 
{% endblock %}
{% block menu %} 
    <li>
        <a class="page-scroll" href="#search">Search</a>
    </li>
{% endblock %}
{% block content %}  
    <!-- Search Section -->
    <section id="search" class="container content-section text-center">
    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">    
                                
        <form class="form-horizontal" role="form" action="/vets/find/" method="POST">
            {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-5 control-label">Which place do you want to search? * </label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" name="location" id="location-input" placeholder="eg. England, London"> 
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-5 control-label">Additional details </label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" name="what" placeholder="eg. Type of pet">   
                    </div>
                </div>
                
                <span>
                    <button type="submit" class="btn btn-success btn-lg adjust">Search!</button>
                </span>                                                                                 
        </form> 
    </div>
    </div>  
    <div class="row">
    <div class="col-lg-8 col-lg-offset-2">  
        <p><h2>OR</h2></p>
        <button type="button" class="btn btn-default btn-lg" onclick="getLocation()">Locate nearby vets!</button>  
        <p id="demo"></p> 
        
    </div>
    </div>                                                             
    </section>

{% endblock %}    

{% block script %} 
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
<script>
var x = document.getElementById("demo");
var location_input = document.getElementById('location-input');
var location_autocomplete = new google.maps.places.Autocomplete(location_input);

function getLocation() {

    if (navigator.geolocation) {
        navigator.geolocation.watchPosition(showPosition);

    } else { 
        x.innerHTML = "Geolocation is not supported by this browser.";}
    }
    
function showPosition(position) {
    var current = location.href;
    var next = current + position.coords.latitude + "/" + position.coords.longitude;
    redirect_it(next);
}

function redirect_it(new_url) {
    location.href =new_url;
}

</script>
{% endblock %}